### ISSUE TITLE
add option 5) Ver inventario in main menu

### ISSUE THREAD

**Issue by Japoivvb** [RovisRon/DAM1-UF5-Shop#1]
1. add new option in main menu, click on it or typing 5 a new window must appear with data loaded in inventory as show in below picture

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb + details

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

![image](https://github.com/RovisRon/DAM1-UF5-Shop/assets/36648472/8576ca4a-8407-45d1-83fe-1bef6c3dc7bf)

**Comment by RovisRon** [comment]
![image](https://github.com/RovisRon/DAM1-UF5-Shop/assets/57545181/5b140cc3-f5d6-47a4-963f-5b40d78b08d0)

Solved!

**Comment by Japoivvb** [comment]
1. ok, but you create a new shop every time you click on option 5. instead use only one
2. ko
3. ko, you use other issue enumeration, 2 instead 1
4. ok
5. ok
good job @RovisRon but you must improve and code more carefully
